### PR TITLE
192 explore caching problem of invalid yaml

### LINKED ISSUE #192: Explore caching problem of invalid YAML
I remember an invalid yaml on my personal https://github.com/trovu/trovu-data-user was extremely hard to get rid off. Browser kept showing an error although the source was already updated.

### PR DESCRIPTION
**Pull request by georgjaehnig**

### CODE REVIEW

**Comment by LuukSuurmeijer** [comment]
Is this fixed? I currently have the issue where trovu keeps loading a stale shortcut.yml with an invalid shortcut definition from cache. I currently cannot use trovu in any way because of this.

**Comment by georgjaehnig** [comment]
I've just opened https://trovu.net/#github=LuukSuurmeijer and I don't see an error, can see the `ethno` shortcut.

I remember the issue was that GitHub sometimes would take up to 5 minutes to update the raw YAML file. So I changed the message after `reload` to

> Shortcuts were reloaded in all namespaces. Changes on your GitHub might require a **reload in 5 minutes** due to caching.

Did you try again after 5 minutes?

**Comment by LuukSuurmeijer** [comment]
Hi Georg, clearing my cache and cookies for trovu fixed the issue. I violated the "keyword arguments" syntax initially, but it was still valid yaml so I thought I might have landed in an edge case with respect to this issue. Thanks for your reply!

**Comment by georgjaehnig** [comment]
> clearing my cache and cookies for trovu fixed the issue.

I wonder if that was causal. Maybe just 5 mins had passed in between? :)

Back then when I was investigating the issue, IIRC this didn't help. I had just to wait exactly 5mins after having accessed the URL last time.

Anyway, good that it works for you now. Don't hesitate to write again if there's an issue!

**Pull request merged**
