### PR TITLE
Update en.yml: added bpo here

### PR DESCRIPTION
**Pull request by Wikinaut**
+ bpo in en.yml

### CODE REVIEW

**Comment by Wikinaut** [comment]
I have no idea why the check fails.

**Comment by georgjaehnig** [comment]
Click on _Details_ and you can see [here](https://github.com/trovu/trovu/actions/runs/9920552010/job/27407561466?pr=422) why the check fails:
```
Problem in namespace en: data/bpo 0/tags/1 must match pattern "^[^ _,;'"\[\]{}*&^%$#@!<>?|\\/]+$"
```
Tags may not contain spaces.

Besides, I don't think it makes sense to move this shortcut to `en`. In `en`, there are only shortcuts related to the English language. For me, this shortcut belongs to `.de`.

**Comment by georgjaehnig** [comment]
Hi @Wikinaut, do you plan to reply to this argument?

> Besides, I don't think it makes sense to move this shortcut to en. In en, there are only shortcuts related to the English language. For me, this shortcut belongs to .de.

**Comment by georgjaehnig** [comment]
Kept in `.de`, added new URLs in 96332b7fa79d11a73665c80df9fe76dec783269d.

**Pull request closed without merging**
