### PR TITLE
Dockerize project

### PR DESCRIPTION
**Pull request by MindfulPol**
Did this to contribute my first PR. 
It allows to setup trovu with 1 command as long as the Host OS has docker. Tested on linux.
Install project: make build
run: make run

### CODE REVIEW

**Comment by georgjaehnig** [comment]
Thanks!

**Comment by RubenRuCh** [comment]
Thanks! Great to be able to run the project with make commands

/tip 5 @MindfulPol <details><summary>How to receive this tip?</summary><br/>@MindfulPol go to [your settings](https://app.opire.dev/settings) and make sure your Stripe account is configured, otherwise you won't be able to receive payments.
@RubenRuCh you can pay the tip in [your dashboard](https://app.opire.dev/dashboard/creator/tips?id=01HW5K7BC6SDYZW2A43NVPG2PG)</details>

**Comment by georgjaehnig** [comment]
Thanks for giving out the tip, @RubenRuCh! 👏

**Comment by MindfulPol** [comment]
Thank you both!!! Opire FTW 🥳 

Please take a look at this [PR](https://github.com/trovu/trovu/pull/359) with a small improvement on the Makefile.

It will allow to run make run / stop without having to remove the container manually (current version you must either run the clean command or manually remove the container)

**Pull request merged**
